### ISSUE TITLE
Error while analyzing

### ISSUE THREAD

**Issue by gkaracayilmaz** [freemansoft/Network-intrusion-dataset-creator#2]
I try to use your code but its always giving the same error on the "ip.proto" line. Can you help me, please. I tried to send only ICMP packets but the result is the same. It gives an error at the same line. And I'm using my own capture file via main.py. My default version of Python is 3.10 but after error, I also tried 3.8.5. Result is the same. Thanks for your help.

![unnamed](https://user-images.githubusercontent.com/22779224/201415284-3d9b102b-8f55-48b0-908d-61f279bbfb2e.png)
![unnamed](https://user-images.githubusercontent.com/22779224/201415366-918522bd-7ff1-4e4f-b70e-0026e856f113.png)

**Comment by freemansoft** [comment]
You probably have non-IP packets in your pcap file. The code knew it couldn't handle in the comments. There are currently no filters for non IP traffic.   

I've updated the code to ignore non-IP packets.  The code will now log the number of unanalyzed IP packets vs non-IP packets.  You have to turn on debug() to see the contents of the unanalyzed packets. Get the latest and test.

It shouldn't be too hard to add packet counts for specific protocols like IPX or other non-IP if someone wants them.

**Comment by gkaracayilmaz** [comment]
Thanks for your help and quick reply. It's working now and as you said some of non-IP packets found in the pcap.
